### ISSUE TITLE
イケてる名前をつける

### ISSUE THREAD

**Issue by hapo31** [hapo31/TAKE#1]

**Comment by wraith13** [comment]
capture-dog

**Comment by wraith13** [comment]
screen-retriever

**Comment by happou31** [comment]
Take screenshot で 竹要素を入れたくなった

**Comment by wraith13** [comment]
犬竹show

**Comment by happou31** [comment]
ロゴです、ご査収ください
![xxx](https://user-images.githubusercontent.com/5890396/59277431-29c35f00-8c9b-11e9-9f6a-cc1d8223dd85.png)

**Comment by hapo31** [comment]
まあ TAKE でええやろ
